/**
 * lib/seeds/obtiznostAPostupCviku.js
 *
 * Ručně psaná česká data pro 47 klíčů v exercise_asset_registry, které mají
 * level = NULL a prázdné instructions_en/instructions_cs — generátor plánu
 * je používá (29 canonical_key), ale jen 4 z nich měly obtížnost a postup.
 *
 * ZDROJ: ručně napsáno pro tento úkol, ne převzato ze zdroje jako
 * free-exercise-db (ten dřív dodával instructions_en, které se jen
 * překládaly — tohle je opačný případ: český text vzniká přímo, protože
 * zdrojová anglická data u těchto klíčů nikdy nebyla).
 *
 * PRAVIDLA OBSAHU (viz zadání úkolu):
 *   - level: 'beginner' | 'intermediate' | 'expert' | null (null jen u
 *     warmup/rest/cooldown — nejde o cvik s obtížností v běžném smyslu)
 *   - mechanic: 'compound' | 'isolation' | null (null jen u warmup/rest/cooldown)
 *   - instructions_cs: 4–7 kroků, rozkazovací způsob, poloha těla + dech +
 *     co hlídat. Žádné obecné fráze ("proveď cvik"), žádné kalorie, žádná
 *     zdravotní tvrzení.
 *   - easier_key / harder_key: canonical_key varianty ze stejné svalové
 *     partie/pohybového vzoru. NULL, když srovnatelná varianta v tomhle
 *     seedu není — žádné vynucené páry jen proto, aby pole nebylo prázdné.
 *
 * Použití: supabase/migrations/20260908120000_obtiznost_a_postup_cviku.sql
 * je z tohohle seedu ručně přepsaná do SQL (UPDATE na 47 řádků) — SOUBOR,
 * NEAPLIKOVANÝ. Tenhle seed je zdroj pravdy pro obsah; migrace i případný
 * budoucí re-seed z něj mají vycházet, ne z kopie v SQL.
 */

/**
 * @typedef {{
 *   level: 'beginner'|'intermediate'|'expert'|null,
 *   mechanic: 'compound'|'isolation'|null,
 *   instructions_cs: string[],
 *   easier_key: string|null,
 *   harder_key: string|null,
 * }} SeedRadekCviku
 */

/** @type {Record<string, SeedRadekCviku>} */
export const SEED_OBTIZNOST_A_POSTUP_CVIKU = {
  bench_press: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Lehni si na lavici, chodidla pevně na zemi, záda i hlavu opřená o podložku.',
      'Úchop veď o něco šíř než ramena, činku sundej ze stojanu nad hrudník.',
      'Nadechni se, spusť činku k hrudníku za 2 sekundy, lokty drž asi 45° od těla.',
      'Jakmile se činka lehce dotkne hrudníku, zastav se.',
      'Vydechni a zatlač činku zpátky nahoru do napnutých paží.',
      'Lopatky drž po celou dobu stažené k sobě a zadek na lavici.',
    ],
    easier_key: 'chest_press',
    harder_key: 'dumbbell_press',
  },
  bent_over_row: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se, chodidla na šířku boků, činka v obou rukou před stehny.',
      'Předkloň se v bocích asi na 45°, záda drž rovná, kolena mírně pokrčená.',
      'Nadechni se a přitáhni činku k pupku, lokty veď těsně kolem těla.',
      'V horní poloze na chvíli stáhni lopatky k sobě.',
      'Vydechni a spouštěj činku zpět dolů pod kontrolou.',
      'Hlavu drž v prodloužení páteře, nezaklánej ji nahoru.',
    ],
    easier_key: 'dumbbell_row',
    harder_key: 'pull_up',
  },
  bicep_curl: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Postav se, chodidla na šířku boků, v každé ruce jedna činka podél těla.',
      'Lokty drž pevně u boků po celou dobu cviku.',
      'Nadechni se a zdvihni činky pokrčením loktů k ramenům.',
      'V horní poloze na chvíli stiskni biceps.',
      'Vydechni a spouštěj činky zpět dolů do napnutých paží.',
      'Zápěstí drž rovně, netrhej činkou pomocí zad.',
    ],
    easier_key: 'machine_bicep_curl',
    harder_key: 'barbell_curl',
  },
  burpee: {
    level: 'expert',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se, chodidla na šířku boků.',
      'Podřepni a polož dlaně na zem před chodidly.',
      'Odkopni nohy vzad do vzporu ležmo, tělo drž v jedné přímce.',
      'Přiskoč nohama zpět k rukám do podřepu.',
      'Vymrsti se z podřepu nahoru do výskoku, paže zvedni nad hlavu.',
      'Doskoč měkce do mírného podřepu a hned navaž dalším opakováním.',
    ],
    easier_key: 'mountain_climber',
    harder_key: null,
  },
  cable_row: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Sedni si ke kladce, chodidla opři o stupačky, kolena mírně pokrčená.',
      'Uchop madlo, záda drž vzpřímená, mírně nakloněná vpřed.',
      'Nadechni se a přitáhni madlo k břichu, lokty veď těsně kolem těla.',
      'V koncové poloze stáhni lopatky k sobě a na chvíli se zastav.',
      'Vydechni a nech paže pomalu se vracet zpět, dokud se lopatky nerozevřou.',
      'Trup drž po celou dobu vzpřímený, nehoupej se dozadu.',
    ],
    easier_key: null,
    harder_key: 'bent_over_row',
  },
  calf_raise: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Postav se na špičky na okraj schodu nebo podložky, paty ve vzduchu.',
      'Drž se opory pro rovnováhu, chodidla na šířku boků.',
      'Nadechni se a zvedni se co nejvýš na špičky.',
      'Nahoře se na chvíli zastav a stiskni lýtka.',
      'Vydechni a spouštěj paty pomalu pod úroveň schodu, dokud neucítíš protažení.',
      'Kolena drž po celou dobu mírně napnutá, nekrč je.',
    ],
    easier_key: null,
    harder_key: 'standing_dumbbell_calf_raise',
  },
  chest_press: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Nastav sedačku tak, aby madla byla v úrovni hrudníku.',
      'Sedni si, záda opři o opěrku, chodidla pevně na zemi.',
      'Nadechni se, uchop madla a lokty drž mírně pod úrovní ramen.',
      'Vydechni a zatlač madla vpřed do téměř napnutých paží, lokty nezamykej.',
      'Nadechni se a pomalu, po 2 sekundách, se vrať do výchozí polohy.',
      'Lopatky drž stažené k opěrce, ramena netahej nahoru k uším.',
    ],
    easier_key: null,
    harder_key: 'bench_press',
  },
  dead_bug: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na záda, paže zvedni kolmo nad ramena, kolena pokrčená v pravém úhlu nad boky.',
      'Dolní záda zatlač k zemi a v této poloze je drž po celou dobu.',
      'Nadechni se a pomalu spouštěj jednu paži za hlavu a opačnou nohu nataženou k zemi.',
      'Zastav se těsně nad zemí, dolní záda se nesmí odlepit.',
      'Vydechni a vrať paži i nohu zpět do výchozí polohy.',
      'Stranu vystřídej a pokračuj plynule, pohyb dělej pomalu.',
    ],
    easier_key: null,
    harder_key: 'barbell_ab_rollout_on_knees',
  },
  deadlift: {
    level: 'expert',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se k čince, chodidla na šířku boků, holeně u tyče.',
      'Ohni se v bocích a kolenou, uchop tyč o něco šíř než nohy, paže napnuté.',
      'Nadechni se, napni záda do rovné polohy, hrudník mírně vytoč vpřed.',
      'Zatlač přes paty a zvedej tyč podél holení do vzpřímeného stoje.',
      'Boky a ramena zvedej zároveň, záda nesmí kulatit.',
      'Vydechni nahoře, pak spouštěj tyč zpět stejnou cestou dolů.',
    ],
    easier_key: 'romanian_deadlift',
    harder_key: null,
  },
  dumbbell_romanian_deadlift: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se, chodidla na šířku boků, v každé ruce jedna činka před stehny.',
      'Kolena nech mírně pokrčená po celou dobu cviku.',
      'Nadechni se a posouvej boky vzad, trup se sklápí vpřed, činky kloužou podél nohou.',
      'Spouštěj se, dokud neucítíš tah v zadní straně stehen, záda drž rovná.',
      'Vydechni a zatlač boky vpřed zpět do vzpřímeného stoje.',
      'Ramena drž stažená, činky těsně u nohou.',
    ],
    easier_key: null,
    harder_key: 'romanian_deadlift',
  },
  dumbbell_row: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Polož jedno koleno a stejnou ruku na lavici, druhá noha pevně na zemi.',
      'Záda drž rovná a rovnoběžná se zemí, v druhé ruce drž činku volně dolů.',
      'Nadechni se a přitáhni činku k boku, loket veď těsně podél těla.',
      'V horní poloze stáhni lopatku k páteři.',
      'Vydechni a spouštěj činku zpět dolů do napnuté paže.',
      'Trup drž nehybný, netoč se za paží.',
    ],
    easier_key: 'cable_row',
    harder_key: 'bent_over_row',
  },
  farmer_carry: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se mezi dvě činky nebo kettlebelly, chodidla na šířku boků.',
      'Podřepni, uchop zátěž v obou rukou, záda drž rovná.',
      'Zatlač přes paty a napřimuj se do vzpřímeného stoje se zátěží podél těla.',
      'Ramena drž stažená dozadu a dolů, hruď mírně vypnutá.',
      'Vykroč a jdi vpřed pevným, kontrolovaným krokem, paže nech viset volně.',
      'Zátěž drž pevně po celou vzdálenost, netoč se do stran.',
    ],
    easier_key: null,
    harder_key: null,
  },
  glute_bridge: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Lehni si na záda, kolena pokrčená, chodidla na šířku boků blízko hýždí.',
      'Paže polož volně podél těla, dlaněmi dolů.',
      'Nadechni se, napni břicho a zatlač přes paty boky vzhůru.',
      'Nahoře stiskni hýždě, tělo od kolen po ramena tvoří rovnou linii.',
      'Vydechni nahoře, pak spouštěj boky zpět dolů pod kontrolou.',
      'Dolní záda drž po celou dobu neutrální, nepropínej se do prohnutí.',
    ],
    easier_key: null,
    harder_key: 'hip_thrust',
  },
  goblet_squat: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se, chodidla o něco šíř než ramena, jednu činku drž oběma rukama u hrudníku.',
      'Nadechni se, napni břicho a spouštěj se ohnutím kolen a boků.',
      'Lokty veď mezi koleny dolů, dokud nejsou boky pod úrovní kolen.',
      'Záda drž rovná, hruď mířící vpřed, kolena ve směru špiček.',
      'Vydechni a zatlač se přes paty zpět nahoru do stoje.',
      'Činku drž těsně u těla po celou dobu pohybu.',
    ],
    easier_key: 'squat',
    harder_key: 'bulgarian_squat',
  },
  hammer_curl: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Postav se, chodidla na šířku boků, v každé ruce jedna činka podél těla, dlaně proti sobě.',
      'Lokty drž pevně u boků po celou dobu cviku.',
      'Nadechni se a zdvihni činky pokrčením loktů, dlaně zůstávají proti sobě.',
      'V horní poloze se na chvíli zastav.',
      'Vydechni a spouštěj činky zpět dolů do napnutých paží.',
      'Zápěstí drž pevně, neklop je do stran.',
    ],
    easier_key: null,
    harder_key: null,
  },
  hamstring_curl: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na břicho do stroje, polštáře opři o kotníky, kolena těsně za okrajem podložky.',
      'Uchop madla po stranách, boky drž přitisknuté k podložce.',
      'Nadechni se a pokrč kolena, přitáhni patu k hýždím.',
      'Nahoře se na chvíli zastav a stiskni zadní stranu stehen.',
      'Vydechni a spouštěj zátěž zpět dolů pod kontrolou.',
      'Boky drž po celou dobu na podložce, nezvedej je.',
    ],
    easier_key: null,
    harder_key: 'dumbbell_romanian_deadlift',
  },
  lat_pulldown: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Sedni si ke kladce, stehna zaklesni pod polstrování.',
      'Uchop tyč nadhmatem o něco šíř než ramena.',
      'Nadechni se a stáhni tyč k horní části hrudníku, lokty táhni dolů a mírně vzad.',
      'V dolní poloze stáhni lopatky k sobě, hrudník mírně vypni.',
      'Vydechni a nech tyč pomalu stoupat zpět do napnutých paží.',
      'Trup drž vzpřímený, nezaklánej se dozadu.',
    ],
    easier_key: null,
    harder_key: 'pull_up',
  },
  leg_press: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Sedni si do stroje, záda i hlavu opři o opěrku, chodidla polož na plošinu na šířku ramen.',
      'Uvolni pojistky a nadechni se.',
      'Spouštěj plošinu pokrčením kolen, dokud nejsou kolena přibližně v pravém úhlu.',
      'Kolena drž ve směru špiček, záda i hlavu nezvedej z opěrky.',
      'Vydechni a zatlač plošinu zpět do skoro napnutých kolen, nezamykej je.',
      'Chodidla drž po celou dobu celou plochou na plošině.',
    ],
    easier_key: null,
    harder_key: 'squat',
  },
  lunges: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se vzpřímeně, chodidla na šířku boků, ruce volně podél těla nebo v bok.',
      'Nadechni se a udělej jednou nohou dlouhý krok vpřed.',
      'Spouštěj se, dokud zadní koleno skoro nedosáhne země, přední koleno nad kotníkem.',
      'Trup drž vzpřímený, váhu drž na přední patě.',
      'Vydechni a odraz se přes přední patu zpět do stoje.',
      'Kroky střídej na obě nohy stejnoměrně.',
    ],
    easier_key: 'leg_press',
    harder_key: 'step_up',
  },
  mountain_climber: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Zaujmi vzpor ležmo, dlaně pod rameny, tělo v jedné přímce.',
      'Napni břicho, ať se boky neprohýbají ani nezvedají.',
      'Nadechni se a přitáhni jedno koleno k hrudníku, druhou nohu nech nataženou.',
      'Vydechni a vrať nohu zpět, ve stejném rytmu vystřídej druhou nohou.',
      'Boky drž po celou dobu v jedné výšce, netrč zadkem nahoru.',
      'Tempo zrychluj jen tak, aby si udržel kontrolu nad polohou boků.',
    ],
    easier_key: 'plank',
    harder_key: 'burpee',
  },
  overhead_press: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se, chodidla na šířku boků, činku drž v úrovni ramen, dlaně vpřed.',
      'Napni břicho a hýždě, ať se dolní záda neprohýbá.',
      'Nadechni se a zatlač činku svisle nad hlavu do napnutých paží.',
      'Hlavu mírně provlékni pod činkou, jakmile prochází kolem obličeje.',
      'Vydechni nahoře, pak spouštěj činku zpět dolů k ramenům pod kontrolou.',
      'Zápěstí drž rovně nad lokty po celou dobu pohybu.',
    ],
    easier_key: 'machine_shoulder_military_press',
    harder_key: null,
  },
  plank: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na břicho a opři se o předloktí a špičky chodidel.',
      'Lokty polož přímo pod ramena, tělo natáhni do rovné linie od hlavy k patám.',
      'Napni břicho a hýždě, boky nesmí klesat ani stoupat nahoru.',
      'Dýchej klidně a plynule po celou dobu výdrže.',
      'Hlavu drž v prodloužení páteře, nedívej se nahoru ani si ji nepokládej.',
      'Pokud boky začnou klesat, cvik ukonči.',
    ],
    easier_key: null,
    harder_key: 'plank_side',
  },
  plank_side: {
    level: 'intermediate',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na bok, opři se o jedno předloktí přímo pod ramenem.',
      'Nohy natáhni jednu na druhou, tělo tvoří rovnou linii od hlavy k patám.',
      'Napni bok a boky zvedni ze země, druhou ruku dej na bok nebo nataž nahoru.',
      'Boky drž zvednuté, netoč trupem dopředu ani dozadu.',
      'Dýchej klidně a plynule po celou dobu výdrže.',
      'Po odcvičeném čase vyměň stranu.',
    ],
    easier_key: 'plank',
    harder_key: null,
  },
  pushup: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Zaujmi vzpor ležmo, dlaně o něco šíř než ramena, tělo v jedné přímce od hlavy k patám.',
      'Napni břicho a hýždě, ať se boky neprohýbají ani nezvedají.',
      'Nadechni se a spouštěj tělo dolů, lokty svírej asi 45° od těla.',
      'Zastav se, jakmile je hrudník pár centimetrů nad zemí.',
      'Vydechni a zatlač se zpět nahoru do napnutých paží.',
      'Bradu drž mírně přitaženou, hlavu neklop dolů ani nezaklánej.',
    ],
    // Kliky na kolenou v katalogu nemáme, kliky na šikmé lavici ano.
    easier_key: 'incline_push_up_wide',
    harder_key: 'dips',
  },
  romanian_deadlift: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se, chodidla na šířku boků, činku drž oběma rukama před stehny.',
      'Kolena nech mírně pokrčená a v této pozici je drž po celou dobu.',
      'Nadechni se a posouvej boky vzad, trup se sklápí vpřed, činka klouže podél nohou.',
      'Spouštěj se, dokud neucítíš tah v zadní straně stehen, záda drž rovná.',
      'Vydechni a zatlač boky vpřed zpět do vzpřímeného stoje.',
      'Činku drž těsně u těla po celou dobu pohybu.',
    ],
    easier_key: 'dumbbell_romanian_deadlift',
    harder_key: 'deadlift',
  },
  russian_twist: {
    level: 'intermediate',
    mechanic: 'isolation',
    instructions_cs: [
      'Sedni si na zem, kolena pokrčená, chodidla mírně nad zemí nebo opřená o podlahu.',
      'Zakloň trup dozadu asi o 45°, záda drž rovná, břicho napnuté.',
      'Ruce spoj před hrudníkem nebo drž zátěž oběma rukama.',
      'Nadechni se a otoč trup k jedné straně, dotkni se rukama u boku.',
      'Vydechni a otoč se plynule na druhou stranu.',
      'Otáčej trupem, nekruť jen paže, boky drž nehybně.',
    ],
    easier_key: 'crunch',
    harder_key: null,
  },
  squat: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se, chodidla na šířku ramen, špičky mírně vytočené ven.',
      'Nadechni se, napni břicho a začni ohýbat kolena a boky zároveň.',
      'Spouštěj se, dokud nejsou stehna aspoň rovnoběžná se zemí.',
      'Kolena drž ve směru špiček, záda rovná, hruď mířící vpřed.',
      'Vydechni a zatlač se zpět nahoru přes paty do vzpřímeného stoje.',
      'Váhu drž po celé chodidle, paty se nesmí zvedat.',
    ],
    easier_key: 'leg_press',
    harder_key: 'goblet_squat',
  },
  superman: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na břicho, paže nataž vpřed, nohy nataž za sebe.',
      'Napni hýždě a břicho, hlavu drž v prodloužení páteře.',
      'Nadechni se a zároveň zvedni paže, hrudník i nohy pár centimetrů nad zem.',
      'Nahoře se na chvíli zastav, dívej se dolů na podložku.',
      'Vydechni a pomalu spouštěj vše zpět dolů pod kontrolou.',
      'Pohyb dělej plynule, netrhej sebou.',
    ],
    easier_key: null,
    harder_key: null,
  },
  tricep_extension: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Postav se čelem ke kladce, uchop lano nebo tyč nadhmatem.',
      'Lokty přitiskni k tělu a drž je nehybně po celou dobu cviku.',
      'Nadechni se a zatlač kladku dolů do napnutých paží.',
      'V dolní poloze na chvíli stiskni triceps.',
      'Vydechni a nech kladku pomalu stoupat zpět, lokty pořád u těla.',
      'Trup drž vzpřímený, nezaklánej se dozadu.',
    ],
    easier_key: 'machine_triceps_extension',
    harder_key: 'tricep_dip',
  },
  box_jump: {
    level: 'expert',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se čelem k bedně, chodidla na šířku boků, paže volně podél těla.',
      'Podřepni a zhoupni paže vzad, ať nabereš rozjezd.',
      'Vymrsti se přes paty a švihem paží vpřed a nahoru, doskoč na bednu oběma nohama najednou.',
      'Doskakuj měkce do podřepu, kolena ve směru špiček.',
      'Narovnej se nahoře na bedně do vzpřímeného stoje.',
      'Z bedny sestup dolů, nikdy neseskakuj zpátky dolů.',
    ],
    easier_key: 'step_up',
    harder_key: null,
  },
  bulgarian_squat: {
    level: 'expert',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se zády ke stoličce, jednu nohu polož nártem na její sedák.',
      'Stojnou nohu posuň dostatečně dopředu, ať koleno nepřečnívá přes špičku.',
      'Nadechni se a spouštěj se pokrčením přední nohy, dokud koleno zadní nohy skoro nedosáhne země.',
      'Trup drž vzpřímený, váhu drž na patě přední nohy.',
      'Vydechni a zatlač se přes patu zpět nahoru do stoje.',
      'Pohyb dělej pomalu, nekymácej se do stran.',
    ],
    easier_key: 'goblet_squat',
    harder_key: null,
  },
  chest_fly: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na lavici, v každé ruce jednu činku nad hrudníkem, dlaně proti sobě.',
      'Lokty mírně pokrč a v této pozici je drž po celou dobu cviku.',
      'Nadechni se a spouštěj paže do stran, dokud neucítíš tah v hrudníku.',
      'Zastav se, jakmile jsou paže v rovině s rameny, níž nechoď.',
      'Vydechni a přitáhni činky obloukem zpět nad hrudník.',
      'Pohyb veď hrudníkem, ne zápěstím ani rameny.',
    ],
    easier_key: null,
    harder_key: null,
  },
  crunch: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na záda, kolena pokrčená, chodidla na zemi na šířku boků.',
      'Ruce polož zkříženě na hrudník nebo lehce za hlavu, lokty do stran.',
      'Nadechni se, napni břicho a zvedni lopatky ze země.',
      'Bradu drž mírně od hrudníku, netahej hlavu rukama.',
      'Vydechni nahoře, pak se pomalu vrať zpět dolů pod kontrolou.',
      'Dolní záda drž po celou dobu přitisknutá k zemi.',
    ],
    easier_key: null,
    harder_key: 'leg_raise',
  },
  dips: {
    level: 'expert',
    mechanic: 'compound',
    instructions_cs: [
      'Uchop bradla, ruce narovnané, tělo drž mírně předkloněné vpřed.',
      'Nadechni se a pomalu spouštěj tělo dolů pokrčením loktů.',
      'Klesej, dokud nejsou ramena přibližně v úrovni loktů, níž nechoď.',
      'Lokty veď mírně od těla, ramena netahej nahoru k uším.',
      'Vydechni a zatlač se zpět nahoru do skoro napnutých paží.',
      'Nohy drž pokrčené a zkřížené, ať se nekymácíš.',
    ],
    easier_key: 'tricep_dip',
    harder_key: null,
  },
  dumbbell_press: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Lehni si na lavici, v každé ruce jednu činku, chodidla na zemi.',
      'Nadechni se, zvedni činky nad hrudník, dlaně směřují vpřed.',
      'Spouštěj činky k hrudníku za 2 sekundy, lokty 45° od těla.',
      'U hrudníku se zastav, zápěstí drž rovně nad lokty.',
      'Vydechni a zatlač činky zpět nahoru, u vrcholu se nedotýkej.',
      'Lopatky drž stažené k lavici po celou dobu série.',
    ],
    easier_key: 'chest_press',
    harder_key: 'bench_press',
  },
  face_pull: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Nastav kladku do výšky očí, uchop lano oběma rukama.',
      'Postav se, chodidla na šířku boků, mírně se zapři vzad.',
      'Nadechni se a táhni lano k obličeji, lokty veď vysoko do stran.',
      'V koncové poloze stáhni lopatky k sobě, palce miř dozadu.',
      'Vydechni a nech lano pomalu se vracet zpět do napnutých paží.',
      'Ramena drž dole, netahej je nahoru k uším.',
    ],
    easier_key: null,
    harder_key: null,
  },
  hip_thrust: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Sedni si na zem, horní záda opři o lavici, činku polož na boky.',
      'Chodidla polož na šířku boků, blízko k hýždím.',
      'Nadechni se, napni břicho a zatlač přes paty boky vzhůru.',
      'Nahoře stiskni hýždě, tělo od kolen po ramena tvoří rovnou linii.',
      'Vydechni nahoře, pak spouštěj boky zpět dolů pod kontrolou.',
      'Bradu drž mírně přitaženou, nezaklánej hlavu vzad.',
    ],
    easier_key: 'glute_bridge',
    harder_key: null,
  },
  incline_bench_press: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Nastav lavici na sklon 30–45°, lehni si, chodidla pevně na zemi.',
      'Úchop veď o něco šíř než ramena, činku sundej nad horní hrudník.',
      'Nadechni se, spusť činku k hornímu hrudníku, lokty 45° od těla.',
      'U hrudníku se na chvíli zastav, neodrážej se.',
      'Vydechni a zatlač činku zpět nahoru do napnutých paží.',
      'Lopatky drž stažené, hlavu opřenou o lavici po celou dobu.',
    ],
    easier_key: 'chest_press',
    harder_key: null,
  },
  jumping_jack: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se vzpřímeně, chodidla u sebe, paže podél těla.',
      'Odraz se a zároveň roznož chodidla širší než ramena.',
      'Ve stejnou chvíli zvedni paže obloukem nad hlavu.',
      'Doskoč měkce na obě chodidla najednou.',
      'Hned se odraz zpátky, chodidla i paže vrať do výchozí polohy.',
      'Udržuj plynulý rytmus a klidné dýchání po celou dobu.',
    ],
    easier_key: null,
    harder_key: null,
  },
  lateral_raise: {
    level: 'beginner',
    mechanic: 'isolation',
    instructions_cs: [
      'Postav se, chodidla na šířku boků, v každé ruce jedna činka podél těla.',
      'Lokty nech mírně pokrčené po celou dobu cviku.',
      'Nadechni se a zvedej paže do stran, dokud nejsou v úrovni ramen.',
      'Nahoře se na chvíli zastav, zápěstí drž mírně níž než lokty.',
      'Vydechni a spouštěj paže pomalu zpět dolů podél těla.',
      'Trupem se nehoupej, pohyb veď jen rameny.',
    ],
    easier_key: 'lateral_raise_with_bands',
    harder_key: null,
  },
  leg_raise: {
    level: 'intermediate',
    mechanic: 'isolation',
    instructions_cs: [
      'Lehni si na záda, nohy natažené, dlaně polož pod hýždě nebo podél těla.',
      'Nadechni se, napni břicho a zatlač dolní záda k zemi.',
      'Zvedej natažené nohy nahoru, dokud nejsou kolmo k zemi.',
      'Vydechni nahoře, pak spouštěj nohy pomalu zpět dolů pod kontrolou.',
      'Jakmile se dolní záda začnou odlepovat od země, pohyb zastav a nohy níž nepouštěj.',
      'Dýchej plynule, nezadržuj dech.',
    ],
    easier_key: 'crunch',
    harder_key: null,
  },
  pull_up: {
    level: 'expert',
    mechanic: 'compound',
    instructions_cs: [
      'Uchop hrazdu nadhmatem o něco šíř než ramena, tělo nech volně viset.',
      'Napni břicho a hýždě, nohy zkřiž nebo drž rovně.',
      'Nadechni se a přitáhni se nahoru, dokud se brada nedostane nad hrazdu.',
      'Lokty táhni dolů a mírně vzad, ramena drž dole od uší.',
      'Vydechni a spouštěj se zpět dolů do napnutých paží pod kontrolou.',
      'Trup drž nehybný, nekopej nohama ani se nehoupej.',
    ],
    easier_key: 'lat_pulldown',
    harder_key: null,
  },
  step_up: {
    level: 'intermediate',
    mechanic: 'compound',
    instructions_cs: [
      'Postav se čelem k bedně nebo stabilní stoličce, chodidla na šířku boků.',
      'Nadechni se, jednu nohu polož celým chodidlem na bednu.',
      'Zatlač přes patu na bedně a vytáhni tělo nahoru, druhou nohu jen dokroč.',
      'Trup drž vzpřímený, nezaklánej se dozadu ani si nepomáhej odrazem druhé nohy.',
      'Vydechni nahoře, pak se pod kontrolou vrať zpět dolů stejnou nohou.',
      'Nohu vyměň po odcvičeném počtu opakování.',
    ],
    easier_key: 'lunges',
    harder_key: 'box_jump',
  },
  tricep_dip: {
    level: 'beginner',
    mechanic: 'compound',
    instructions_cs: [
      'Sedni si na kraj lavice, dlaně vedle boků, prsty směrem k tělu.',
      'Nohy natáhni před sebe, paty na zemi, boky posuň před hranu lavice.',
      'Nadechni se a spouštěj boky dolů pokrčením loktů k 90°.',
      'Lokty drž vzadu za tělem, ne do stran.',
      'Vydechni a zatlač se zpět nahoru do napnutých paží.',
      'Ramena drž dole, od uší, po celou dobu pohybu.',
    ],
    easier_key: null,
    harder_key: 'dips',
  },
  warmup: {
    level: null,
    mechanic: null,
    instructions_cs: [
      'Začni volnou chůzí nebo klusem na místě po dobu 2–3 minut, dýchej klidně nosem.',
      'Zařaď kroužení pažemi vpřed i vzad, každým směrem 10krát.',
      'Přidej dynamické výpady vpřed se současným kroužením trupu do stran.',
      'Zařaď dřepy s vlastní vahou pomalým tempem, 10–15 opakování.',
      'Postupně zvyšuj tempo pohybů, ale dýchání drž pravidelné a plynulé.',
      'Rozcvičku ukonči, až ucítíš zahřátí svalů a mírně zrychlený tep.',
    ],
    easier_key: null,
    harder_key: null,
  },
  rest: {
    level: null,
    mechanic: null,
    instructions_cs: [
      'Vyber klidné tempo chůze, při kterém se dá bez potíží mluvit.',
      'Drž vzpřímené držení těla, ramena uvolněná, paže se volně houpou podél těla.',
      'Dýchej pravidelně nosem, výdech nech plynulý ústy nebo nosem.',
      'Udržuj stejné tempo po celou naplánovanou dobu chůze.',
      'Pokud ucítíš únavu, zpomal tempo, ale procházku nepřerušuj úplně.',
      'Zakonči procházku postupným zpomalením posledních 2–3 minut.',
    ],
    easier_key: null,
    harder_key: null,
  },
  cooldown: {
    level: null,
    mechanic: null,
    instructions_cs: [
      'Zpomal tempo pohybu a přejdi na klidnou chůzi po dobu 1–2 minut.',
      'Protáhni zadní stranu stehen předklonem s mírně pokrčenými koleny, vydrž 20–30 sekund.',
      'Protáhni lýtka opřením o zeď s nataženou zadní nohou, vydrž 20–30 sekund na každou stranu.',
      'Protáhni hrudník a ramena zapažením a mírným otevřením hrudníku, vydrž 20–30 sekund.',
      'Dýchej pomalu a zhluboka, nádech nosem, výdech ústy.',
      'Strečink ukonči, až ucítíš uvolnění protahovaných svalů, ne bolest.',
    ],
    easier_key: null,
    harder_key: null,
  },
};

export function seedKlice() {
  return Object.keys(SEED_OBTIZNOST_A_POSTUP_CVIKU);
}
