/**
 * Static alias + canonical display map (mirrors public.ingredient_aliases seed).
 * Client bundle uses this; DB table allows ops to extend without redeploy (sync script optional).
 */

/** @type {Record<string, string>} normalized canonical key → Czech display name */
export const CANONICAL_DISPLAY = Object.freeze({
  'arasidove maslo': 'arašídové máslo',
  avokado: 'avokádo',
  banan: 'banán',
  'bila ryba': 'bílá ryba',
  'bily jogurt': 'bílý jogurt',
  brambory: 'brambory',
  brokolice: 'brokolice',
  'celozrnny chleb': 'celozrnný chléb',
  'celozrnny toast': 'celozrnný toast',
  'cerstve ovoce': 'čerstvé ovoce',
  cesnek: 'česnek',
  cibule: 'cibule',
  citron: 'citron',
  'citronova stava': 'citronová šťáva',
  cocka: 'čočka',
  cottage: 'cottage',
  cuketa: 'cuketa',
  fazole: 'fazole',
  'hovezi maso': 'hovězí maso',
  jablko: 'jablko',
  jahody: 'jahody',
  'javorovy sirup': 'javorový sirup',
  kefir: 'kefír',
  'kruti prsa': 'krůtí prsa',
  'kruti prso': 'krůtí prso',
  'kureci prsa': 'kuřecí prsa',
  'kureci prso': 'kuřecí prso',
  'libove hovezi maso': 'libové hovězí maso',
  'libove maso (napr. veprove)': 'libové maso (např. vepřové)',
  losos: 'losos',
  maslo: 'máslo',
  med: 'med',
  mleko: 'mléko',
  mrkev: 'mrkev',
  musli: 'müsli',
  okurka: 'okurka',
  olej: 'olej',
  'olivovy olej': 'olivový olej',
  orechy: 'ořechy',
  'ovesne vlocky': 'ovesné vločky',
  paprika: 'paprika',
  'paprika (cervena)': 'paprika (červená)',
  pepr: 'pepř',
  'proteinovy prasek': 'proteinový prášek',
  quinoa: 'quinoa',
  rajce: 'rajče',
  'ryba (napr. losos)': 'ryba (např. losos)',
  'ryba (napr. treska)': 'ryba (např. treska)',
  ryze: 'rýže',
  'ryze (bila)': 'rýže (bílá)',
  'salat (napr. ledovy)': 'salát (např. ledový)',
  skorice: 'skořice',
  'sladke brambory': 'sladké brambory',
  'smes salatu': 'směs salátů',
  'sojova omacka': 'sojová omáčka',
  spenat: 'špenát',
  sunka: 'šunka',
  syr: 'sýr',
  testoviny: 'těstoviny',
  'tunak (v konzerve)': 'tuňák (v konzervě)',
  tvaroh: 'tvaroh',
  vejce: 'vejce',
  'veprova panenka': 'vepřová panenka',
  zelenina: 'zelenina',
  jogurt: 'jogurt',
  protein: 'proteinový prášek',
  tunak: 'tuňák (v konzervě)',
  mandle: 'ořechy',
  'celozrnne pecivo': 'celozrnný chléb',
  kuskus: 'kuskus',
  strouhanka: 'strouhanka',
  sul: 'sůl',
  tofu: 'tofu',
  hrasek: 'hrášek',
});

/** @type {Array<[string, string]>} [aliasNormalized, canonicalNormalized] longest-first at runtime */
export const ALIAS_PAIRS = Object.freeze([
  ['tunak ve vlastni stave', 'tunak (v konzerve)'],
  ['tunak v konzerve', 'tunak (v konzerve)'],
  ['celozrnne pecivo', 'celozrnny chleb'],
  ['celozrnný chléb', 'celozrnny chleb'],
  ['proteinovy prasek', 'proteinovy prasek'],
  ['protein', 'proteinovy prasek'],
  ['bileho jogurtu', 'bily jogurt'],
  ['bily jogurt', 'bily jogurt'],
  ['jogurt', 'bily jogurt'],
  ['kureci prso', 'kureci prsa'],
  ['kruti prso', 'kruti prsa'],
  ['mandle', 'orechy'],
  ['tunak', 'tunak (v konzerve)'],
]);

/** @type {Record<string, number>} unit (normalized ascii) → grams per 1 unit */
export const UNIT_TO_GRAMS = Object.freeze({
  lzicka: 5,
  lzice: 15,
});
