/**
 * České zobrazení názvů surovin ze Spoonacular (API často vrací anglicky).
 * Pouze UI / plán — výživa a ID receptu zůstávají ze zdroje API.
 */

const MAP = {
  eggs: 'vejce',
  egg: 'vejce',
  'large eggs': 'vejce',
  vinegar: 'ocet',
  water: 'voda',
  'coconut oil': 'kokosový olej',
  leek: 'pórek',
  'baby beet greens': 'listy červené řepy',
  'beet greens': 'mangold / listy řepy',
  garlic: 'česnek',
  'garlic cloves': 'stroužky česneku',
  cloves: 'stroužky',
  'juice of lemon': 'citronová šťáva',
  lemon: 'citron',
  'parmesan cheese': 'parmazán',
  parmesan: 'parmazán',
  'greek yogurt': 'řecký jogurt',
  yogurt: 'jogurt',
  'dark chocolate chips': 'čokoládové pecičky',
  'chocolate chips': 'čokoládové pecičky',
  oats: 'oves',
  oatmeal: 'ovesné vločky',
  banana: 'banán',
  spinach: 'špenát',
  tomato: 'rajče',
  tomatoes: 'rajčata',
  onion: 'cibule',
  chicken: 'kuře',
  salmon: 'losos',
  tuna: 'tuňák',
  shrimp: 'krevety',
  rice: 'rýže',
  pasta: 'těstoviny',
  butter: 'máslo',
  milk: 'mléko',
  cream: 'smetana',
  salt: 'sůl',
  pepper: 'pepř',
  oil: 'olej',
  'olive oil': 'olivový olej',
  flour: 'mouka',
  sugar: 'cukr',
  honey: 'med',
  nuts: 'ořechy',
  almonds: 'mandle',
  avocado: 'avokádo',
  bread: 'chléb',
  cheese: 'sýr',
  mozzarella: 'mozzarella',
  basil: 'bazalka',
  parsley: 'petržel',
  cilantro: 'koriandr',
  ginger: 'zázvor',
  cumin: 'kmín',
  paprika: 'paprika',
  broccoli: 'brokolice',
  carrot: 'mrkev',
  carrots: 'mrkev',
  cucumber: 'okurka',
  lettuce: 'salát',
  potato: 'brambory',
  potatoes: 'brambory',
  beef: 'hovězí',
  pork: 'vepřové',
  turkey: 'krůta',
  tofu: 'tofu',
  lentils: 'čočka',
  beans: 'fazole',
  chickpeas: 'cizrna',
  quinoa: 'quinoa',
  apple: 'jablko',
  berries: 'bobule',
  blueberries: 'borůvky',
  strawberries: 'jahody',
  'rolled oats': 'ovesné vločky',
  oatmeal: 'ovesné vločky',
  'creamed wildflower honey': 'med',
  honey: 'med',
  applesauce: 'jablečné pyré',
  raspberries: 'maliny',
  raspberry: 'malina',
  'vanilla extract': 'vanilkový extrakt',
  pistachios: 'pistácie',
  pistachio: 'pistácie',
  'bean sprouts': 'fazolové klíčky',
  sprouts: 'klíčky',
  'bok choy': 'pak choi',
  spaghetti: 'špagety',
  'soy sauce': 'sójová omáčka',
  'soya sauce': 'sójová omáčka',
  mushroom: 'houby',
  mushrooms: 'houby',
  'peanut oil': 'arašídový olej',
  scallions: 'jarní cibulka',
  scallion: 'jarní cibulka',
  'chicken breast': 'kuřecí prsa',
  'chicken breasts': 'kuřecí prsa',
  'chicken broth': 'kuřecí vývar',
  'kuře broth': 'kuřecí vývar',
  broth: 'vývar',
  stock: 'vývar',
  'vegetable stock': 'zeleninový vývar',
  'bell pepper': 'paprika',
  peppers: 'papriky',
  'poached salmon': 'losos',
  'green onions': 'jarní cibulka',
  'rice vinegar': 'rýžový ocet',
  'sesame oil': 'sezamový olej',
  'vegetable oil': 'rostlinný olej',
  noodles: 'nudle',
  tofu: 'tofu',
  edamame: 'edamame',
  'soy milk': 'sójové mléko',
  'coconut milk': 'kokosové mléko',
  'brown sugar': 'hnědý cukr',
  'maple syrup': 'javorový sirup',
  'baking powder': 'prášek do pečiva',
  'baking soda': 'jedlá soda',
  'chili sauce': 'omáčka chilli',
  'rice wine': 'rýžové víno',
  'worcestershire sauce': 'worcesterská omáčka',
  'fish sauce': 'rybí omáčka',
  'hot sauce': 'pálivá omáčka',
  'sour cream': 'zakysaná smetana',
  'cream cheese': 'smetanový sýr',
  'cheddar cheese': 'čedar',
  bacon: 'slanina',
  ham: 'šunka',
  sausage: 'klobása',
  prawns: 'krevety',
  cod: 'treska',
  tilapia: 'tilapie',
  zucchini: 'cuketa',
  aubergine: 'lilek',
  eggplant: 'lilek',
  cabbage: 'zelí',
  cauliflower: 'květák',
  peas: 'hrášek',
  corn: 'kukuřice',
  dill: 'kopr',
  mint: 'máta',
  rosemary: 'rozmarýn',
  thyme: 'tymián',
  oregano: 'oregáno',
  cinnamon: 'skořice',
  nutmeg: 'muškátový oříšek',
  'whole cloves': 'hřebíček (koření)',
  'star anise': 'badyán',
  'bay leaf': 'bobkový list',
  yeast: 'droždí',
  'baking chocolate': 'čokoláda na pečení',
  cocoa: 'kakao',
  'coconut flakes': 'kokosové lupínky',
  'sunflower seeds': 'slunečnicová semínka',
  'chia seeds': 'chia semínka',
  'flax seeds': 'lněná semínka',
  'pumpkin seeds': 'dýňová semínka',
  raisins: 'rozinky',
  dates: 'datle',
  orange: 'pomeranč',
  lime: 'limeta',
  grapefruit: 'grapefruit',
  peach: 'broskev',
  pear: 'hruška',
  plum: 'švestka',
  cherry: 'třešně',
  grapes: 'hrozny',
  melon: 'meloun',
  watermelon: 'meloun vodní',
  oats: 'ovesné vločky',
};

/** Jednotky ze Spoonacular (často anglicky) → české zobrazení v plánu / e-mailu. */
const UNIT_MAP = {
  '': '',
  g: 'g',
  gram: 'g',
  grams: 'g',
  kg: 'kg',
  ml: 'ml',
  l: 'l',
  liter: 'l',
  litres: 'l',
  cup: 'šálka',
  cups: 'šálky',
  tbsp: 'polévková lžíce',
  tablespoon: 'polévková lžíce',
  tablespoons: 'polévkové lžíce',
  tsp: 'lžička',
  teaspoon: 'lžička',
  teaspoons: 'lžičky',
  tbs: 'polévková lžíce',
  tbsps: 'polévkové lžíce',
  oz: 'unce',
  ounce: 'unce',
  ounces: 'unce',
  lb: 'libra',
  lbs: 'libry',
  pound: 'libra',
  pounds: 'libry',
  clove: 'stroužek',
  cloves: 'stroužky',
  medium: 'ks (střední)',
  large: 'ks (velký)',
  small: 'ks (malý)',
  leaf: 'list',
  leaves: 'listy',
  serving: 'porce',
  servings: 'porce',
  pinch: 'špetka',
  dash: 'kapka',
  can: 'konzerva',
  package: 'balení',
  stalk: 'stonky',
  stalks: 'stonky',
  slice: 'plátek',
  slices: 'plátky',
  piece: 'kus',
  pieces: 'kusy',
  sprig: 'snítka',
  sprigs: 'snítky',
  handful: 'hrst',
  bunch: 'snop',
  head: 'hlávka',
  rack: 'řada',
  filet: 'filet',
  fillet: 'filet',
  fillets: 'filety',
  string: 'svazek',
  strings: 'svazky',
};

/**
 * @param {string|null|undefined} raw
 * @returns {string}
 */
export function ingredientNameForDisplayCs(raw) {
  if (raw == null || typeof raw !== 'string') return '';
  const t = raw.trim();
  if (!t) return '';
  const key = t.toLowerCase().replace(/\s+/g, ' ');
  if (MAP[key]) return MAP[key];
  const firstWord = key.split(/[\s,;(]/)[0];
  if (firstWord && MAP[firstWord]) {
    const rest = key.slice(firstWord.length).trim();
    return rest ? `${MAP[firstWord]} ${rest}` : MAP[firstWord];
  }
  return t;
}

/**
 * @param {string|null|undefined} raw
 * @returns {string}
 */
export function ingredientUnitForDisplayCs(raw) {
  if (raw == null || typeof raw !== 'string') return '';
  const t = raw.trim();
  if (!t) return '';
  const key = t.toLowerCase().replace(/\./g, '');
  if (UNIT_MAP[key]) return UNIT_MAP[key];
  const norm = key.replace(/s$/i, '');
  if (UNIT_MAP[norm] && key !== norm) {
    return UNIT_MAP[norm];
  }
  return t;
}
