-- =============================================================================
-- STEP 1 — REQUIRED TABLES (create if not exists)
-- Missing from existing SQL docs; inferred from active codebase usage.
-- Safe to run multiple times.
-- =============================================================================

-- ai_generated_plans
-- Stores weekly AI plans per user. Generated by generatePlan.js.
create table if not exists ai_generated_plans (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid,
  email           text,
  plan_type       text,
  plan_html       text,
  plan_markdown   text,
  daily_calories  numeric,
  macros          jsonb,
  workout_plan    jsonb,
  exercises_data  jsonb,
  meal_plan       jsonb,
  generated_by    text,
  generation_prompt text,
  user_context    jsonb,
  valid_from      date,
  valid_until     date,
  is_active       boolean default true,
  created_at      timestamp default now()
);

-- body_metrics
-- User physical metrics collected during onboarding and profile updates.
create table if not exists body_metrics (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid,
  email           text,
  name            text,
  gender          text,
  age             integer,
  height_cm       numeric,
  weight_kg       numeric,
  activity        text,
  stress          text,
  occupation      text,
  goal            text,
  weekly_sessions integer,
  diet_type       text,
  preferences     text,
  calories_target numeric,
  workout_days    text,
  created_at      timestamp default now(),
  updated_at      timestamp default now()
);

-- Reference: tables defined in other docs files:
--   ai_agents, ai_agent_tools, ai_agent_settings → supabase_multi_agent.sql
--   user_ai_memory                                → supabase_multi_agent.sql
--   ai_tasks                                      → supabase_ai_tasks.sql
--   user_checkins                                 → supabase_user_checkins.sql
--   meal_metadata_cache, exercise_metadata_cache  → supabase_enrichment_cache.sql
--   ai_config                                     → supabase_ai_config.sql
