-- CREATE TABLE IF NOT EXISTS pro body_metrics a ai_generated_plans.
-- Spouští se jen když tabulky neexistují (nové prostředí). Existující DB zůstane beze změny.

CREATE TABLE IF NOT EXISTS public.body_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  email text,
  name text,
  gender text,
  age integer,
  height_cm numeric,
  weight_kg numeric,
  activity text,
  stress_level text,
  occupation text,
  goal text,
  freq_choice text,
  weekly_sessions_user integer,
  diet_type text,
  dietary_restrictions text,
  foods_to_avoid text,
  notes text,
  program text DEFAULT 'START',
  body_fat_percentage numeric,
  water_percentage numeric,
  bmi numeric,
  tdee numeric,
  calories_target numeric
);

CREATE TABLE IF NOT EXISTS public.ai_generated_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  email text,
  plan_type text,
  plan_html text,
  plan_markdown text,
  daily_calories integer,
  macros jsonb DEFAULT '{}',
  workout_plan jsonb DEFAULT '{}',
  exercises_data jsonb DEFAULT '{}',
  meal_plan jsonb DEFAULT '{}',
  generated_by text,
  generation_prompt text,
  user_context jsonb,
  valid_from date,
  valid_until date,
  is_active boolean DEFAULT true,
  email_sent boolean DEFAULT false
);

COMMENT ON TABLE public.body_metrics IS 'Metriky uživatelů (váha, výška, aktivita, cíl, strava) – z registrace a profilu.';
COMMENT ON TABLE public.ai_generated_plans IS 'AI generované plány (OpenAI Assistant) – jídelníček, trénink, makra.';
