CREATE TABLE IF NOT EXISTS public.ingredient_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias_normalized text NOT NULL,
  canonical_normalized text NOT NULL,
  display_alias_cs text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ingredient_aliases_alias_normalized_key UNIQUE (alias_normalized)
);

ALTER TABLE public.ingredient_aliases ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY ingredient_aliases_service_read ON public.ingredient_aliases FOR SELECT TO service_role USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY ingredient_aliases_service_write ON public.ingredient_aliases FOR ALL TO service_role USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.ingredient_normalization_misses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_name text NOT NULL,
  plan_id uuid REFERENCES public.ai_generated_plans(id) ON DELETE CASCADE,
  seen_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ingredient_normalization_misses_raw_plan_key UNIQUE (raw_name, plan_id)
);

ALTER TABLE public.ingredient_normalization_misses ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY ingredient_normalization_misses_service ON public.ingredient_normalization_misses FOR ALL TO service_role USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

INSERT INTO public.ingredient_aliases (alias_normalized, canonical_normalized, display_alias_cs) VALUES
  ('tunak ve vlastni stave', 'tunak (v konzerve)', 'tuňák ve vlastní šťávě'),
  ('celozrnne pecivo', 'celozrnny chleb', 'celozrnné pečivo'),
  ('protein', 'proteinovy prasek', 'protein'),
  ('bileho jogurtu', 'bily jogurt', 'bílého jogurtu'),
  ('jogurt', 'bily jogurt', 'jogurt'),
  ('kureci prso', 'kureci prsa', 'kuřecí prso'),
  ('kruti prso', 'kruti prsa', 'krůtí prso'),
  ('mandle', 'orechy', 'mandle'),
  ('tunak', 'tunak (v konzerve)', 'tuňák')
ON CONFLICT (alias_normalized) DO NOTHING;;
