INSERT INTO ingredient_aliases (alias_normalized, canonical_normalized, display_alias_cs)
SELECT v.a, v.c, v.a
FROM (VALUES
  ('sul a pepr','sul'),
  ('mlety pepr','pepr'),
  ('morska sul','sul'),
  ('kosher sul','sul'),
  ('bezna sul','sul'),
  ('cesnekova sul','sul'),
  ('peprove vlocky','pepr'),
  ('kajensky pepr','pepr'),
  ('cerstve mlety pepr','pepr'),
  ('extra panensky olivovy olej','olivovy olej'),
  ('rostlinny olej','olej'),
  ('hroznovy olej','olej'),
  ('sezamovy olej','olej'),
  ('arasidovy olej','olej'),
  ('strouzky cesneku','cesnek'),
  ('strouzek cesneku','cesnek'),
  ('cesnekove strouzky','cesnek'),
  ('cesnek (drceny)','cesnek'),
  ('cherry rajcata','rajce'),
  ('rajcata','rajce'),
  ('rajcata hroznova','rajce'),
  ('papriky','paprika'),
  ('mrkve','mrkev'),
  ('baby spenat','spenat'),
  ('listovy spenat','spenat'),
  ('bazalkove listy','bazalka'),
  ('matove listy','mata'),
  ('listy koriandru','koriandr'),
  ('cerstvy koriandr','koriandr'),
  ('petrzel na ozdobu','petrzel'),
  ('filet lososa','losos'),
  ('filety z lososa','losos'),
  ('lososove filety','losos'),
  ('vanilkovy jogurt','bily jogurt'),
  ('nizkotucny jogurt','bily jogurt'),
  ('broskve','broskev'),
  ('zelene cibulky','jarni cibulka'),
  ('limetkova stava','citronova stava'),
  ('stava z citronu','citronova stava'),
  ('limetkova kura','citronova kura'),
  ('citronove klinky','citron'),
  ('makarony','testoviny'),
  ('kolinka','testoviny'),
  ('lasagne','testoviny'),
  ('cavatappi testoviny','testoviny'),
  ('cavatelli','testoviny'),
  ('basmati ryze','ryze'),
  ('hneda ryze','ryze'),
  ('mlete hovezi maso','hovezi maso'),
  ('cheddar syr','cheddar'),
  ('extra ostry cedar','cheddar'),
  ('ostre cedar','cheddar'),
  ('feta syr','feta'),
  ('syr monterrey jack','syr'),
  ('baby portobello houby','houby'),
  ('ovoce','cerstve ovoce'),
  ('bobule','boruvky'),
  ('agavovy sirup','agave'),
  ('chilli papricky','chili papricky'),
  ('chilli papricka','chili papricky'),
  ('chili papricka','chili papricky'),
  ('scotch bonnet paprika','chili papricky'),
  ('slehacka','smetana'),
  ('vlasske orechy','orechy'),
  ('brambora','brambory'),
  ('chleb','celozrnny chleb'),
  ('batat','sladke brambory'),
  ('panko strouhanka','strouhanka'),
  ('mlety kurkuma','kurkuma'),
  ('krevetky','krevety')
) AS v(a,c)
WHERE NOT EXISTS (
  SELECT 1 FROM ingredient_aliases ia WHERE ia.alias_normalized = v.a
);;
