-- Seed trainer supporting documents. Idempotent: inserts only when source_id not present.
-- Run after 20260323_ai_supporting_documents.sql

INSERT INTO ai_supporting_documents (agent_slug, title, summary, key_facts, source_id, enabled, sort_order)
SELECT 'trainer', 'Zásady výživy Body & Mind ON', 'Při sestavování jídelníčku: respektuj diet_type (standard/vegetarian/vegan), denní kalorický cíl a bílkoviny (cca 1,4–1,8 g/kg podle cíle). Preferuj běžná, dobře mapovatelná jídla pro Spoonacular (např. kuřecí prsa s rýží, ovesná kaše, losos s bramborami, čočka, tofu stir-fry, zeleninový salát s vejcem, tvaroh s ovocem). Vyhni se exotickým názvům bez match v databázi.', '["Respektuj diet_type a preferences uživatele.", "Bílkoviny podle cíle: udržování 1,4 g/kg, růst svalů 1,6–1,8 g/kg.", "Pouze jídla vhodná pro Spoonacular lookup – krátké, běžné názvy.", "Nevymýšlej kreativní exotiku bez ověření v API."]'::jsonb, 'seed-nutrition-1', true, 0
WHERE NOT EXISTS (SELECT 1 FROM ai_supporting_documents WHERE agent_slug = 'trainer' AND source_id = 'seed-nutrition-1');

INSERT INTO ai_supporting_documents (agent_slug, title, summary, key_facts, source_id, enabled, sort_order)
SELECT 'trainer', 'Povolené cviky a struktura tréninku', 'Používej pouze cviky z povoleného seznamu: Dřepy, Kliky, Přítahy v předklonu, Výpady, Prkno, Superman, Mrtvý tah, Rumunský mrtvý tah, Tlaky na hrudník, Tlaky nad hlavu, Rozcvička, Závěr, Strečink, Mobilita, Lehká procházka, Odpočinek, Shyby, Přítahy, Boční prkno, Mountain climber, Rozpažky, Bicepsový zdvih, Tricepsové tlaky, Tlaky nohama. U každého tréninkového dne uveď konkrétní cviky a délky; u odpočinkových dnů „Odpočinek“ nebo „Lehká procházka 20–30 min“. Žádné názvy mimo seznam (např. Bulgarian split squat nahraď výpady nebo dřepy).', '["Pouze cviky z oficiálního povoleného seznamu.", "Strukturní položky: Rozcvička, Závěr, Odpočinek, Lehká procházka – vždy povolené.", "U neznámého cviku použij bezpečný fallback ze seznamu.", "Trénink tento den: konkrétní cviky + délky u tréninkových dnů."]'::jsonb, 'seed-training-1', true, 1
WHERE NOT EXISTS (SELECT 1 FROM ai_supporting_documents WHERE agent_slug = 'trainer' AND source_id = 'seed-training-1');

INSERT INTO ai_supporting_documents (agent_slug, title, summary, key_facts, source_id, enabled, sort_order)
SELECT 'trainer', 'Struktura týdenního plánu a výstup', 'Plán musí obsahovat: sekci Jídelníček (h3), sekci Trénink (h3), pro každý ze 7 dní Snídaně / Oběd / Večeře a blok „Trénink tento den“ (u tréninkových dnů konkrétní cviky, u odpočinku např. Odpočinek nebo Lehká procházka). Dále sekce Regenerace, Suplementace, Nákupní seznam, Mindset. Vždy vracej kompletní plán – nikdy jen Regeneraci/Suplementaci/Mindset bez jídelníčku a tréninku. Výstup pouze platný JSON: ok, metrics (bmr, tdee, calories, protein_g, carbs_g, fat_g), html; volitelně mindset_tip, shopping_list.', '["Povinné: Jídelníček + Trénink + 7 dní s jídly a „Trénink tento den“.", "Zakázáno: vrátit jen Regeneraci/Suplementaci/Mindset bez kompletního plánu.", "JSON: ok, metrics, html; volitelně mindset_tip, shopping_list.", "HTML struktura musí odpovídat zobrazení v aplikaci."]'::jsonb, 'seed-structure-1', true, 2
WHERE NOT EXISTS (SELECT 1 FROM ai_supporting_documents WHERE agent_slug = 'trainer' AND source_id = 'seed-structure-1');
